DROP SCHEMA IF EXISTS Epers_Ej1;
CREATE SCHEMA Epers_Ej1;

USE Epers_Ej1;

CREATE TABLE `Epers_Ej1`.`Aerolinea` (
  `ID` INTEGER  NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(255)  NOT NULL,
  `CODIGO` VARCHAR(3)  NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `CODIGO`(`CODIGO`)
)
ENGINE = InnoDB;
